# Development Docker Compose for DAG Generator
# Uses development versions of services with hot reload

version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build: ./backend
    container_name: dag-generator-backend-dev
    ports:
      - "5002:5002"
    volumes:
      - ./projects:/app/projects:ro
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    restart: unless-stopped

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dag-generator-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5002
    restart: unless-stopped
    depends_on:
      - backend
    stdin_open: true
    tty: true
