# Full Stack Docker Compose for DAG Generator
#
# This will orchestrate both backend and frontend services when frontend is ready.
# For now, it just runs the backend service.

version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: dag-generator-backend
    ports:
      - "5002:5002"
    volumes:
      - ./projects:/app/projects:ro
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      # Configure which project folder to analyze (default: finance)
      # - DAG_TARGET_PROJECT=finance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service placeholder (to be added later)
  frontend:
    build: ./frontend
    container_name: dag-generator-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
